### ISSUE TITLE
ICCAD 2015 benchmarks

### ISSUE THREAD

**Issue by gxydbc** [lamda-bbo/macro-regulator#5]
I couldn't find the ICCAD 2015 benchmarks in the repository. You mentioned in the paper that modifications were made to the area of the cases. Could you please specify how these modifications were made? The shapes of the ICCAD 2015 benchmarks I have are different from those in your paper. Thanks!

**Comment by gxydbc** [comment]
> 谢谢你指出这一点。我们已将数据集上传到 google drive。请检查此提交。[6605EAD](https://github.com/lamda-bbo/macro-regulator/commit/6605ead89090b1a8c20c7f3144f2df212e7825c7)

The experimental section of the paper states, "Therefore, we scale down the chip’s placement area, presenting further challenges for the compared methods." However, it seems that the benchmarks you provided have not been modified. Could you please let me know how to make the necessary changes? Thank you!

**Comment by gxydbc** [comment]
> Thanks for pointing this out. We have upload the data set in google drive. Please check this commit. [6605ead](https://github.com/lamda-bbo/macro-regulator/commit/6605ead89090b1a8c20c7f3144f2df212e7825c7)

The experimental section of the paper states, "Therefore, we scale down the chip’s placement area, presenting further challenges for the compared methods." However, it seems that the benchmarks you provided have not been modified. Could you please let me know how to make the necessary changes? Thank you!

**Comment by DukeTomlist** [comment]
@gxydbc We did not directly modify the original benchmark. Instead, we made corresponding modifications and constraints during the runtime of our code (such as modifying the row information in the `.def` file).
